export type AssetTag = { id: string; name: string; value: string; color: string | null };
export type AssetAlbum = { id: string; name: string };
export type AssetStack = { id: string; primaryAssetId: string; assetCount: number; assets: string[] };
export type AssetRecord = { id: string; owner_id: string | null; library_id: string | null; asset_type: 'IMAGE' | 'VIDEO' | 'AUDIO' | 'OTHER'; original_file_name: string; original_path: string | null; original_mime_type: string | null; checksum: string | null; file_size_bytes: number | null; width: number | null; height: number | null; duration: number | null; file_created_at: string; file_modified_at: string; local_date_time: string | null; immich_created_at: string | null; immich_updated_at: string | null; is_favorite: boolean; is_archived: boolean; is_offline: boolean; is_edited: boolean; has_metadata: boolean; visibility: string | null; live_photo_video_id: string | null; tags: AssetTag[]; albums?: AssetAlbum[]; stack: AssetStack | null; synced_at: string };
export type AssetDetailRecord = AssetRecord & { albums: AssetAlbum[] };
export type TrashAssetRecord = { id: string; type: AssetRecord['asset_type']; original_file_name: string; original_mime_type: string | null; width: number | null; height: number | null; duration: number | null; taken_at: string; file_modified_at: string; is_favorite: boolean; is_archived: boolean; restore_path: string | null; file_size_bytes?: number | null; library_id?: string | null; is_offline?: boolean };
export type AlbumRecord = { id: string; album_name: string; description: string; album_thumbnail_asset_id: string | null; asset_count: number; immich_created_at: string; immich_updated_at: string; synced_at: string };
export type TagRecord = { id: string; tag_name: string; tag_value: string; color: string | null; asset_count: number; synced_at: string };
export type AlbumCreateInput = { name: string; description?: string }; export type AlbumUpdateInput = { name?: string; description?: string }; export type TagCreateInput = { name: string; color?: string | null; parentId?: string }; export type TagUpdateInput = { color?: string | null }; export type AlbumCreateArgs = [name: string, description?: string]; export type TagCreateArgs = [name: string, color?: string | null, parentId?: string];
export type TagHierarchyRow = { id: string; name: string; path: string; parent: string; assets: number; children: number; color: string | null; synthetic: boolean; realTagIds: string[] };
export type MutationFailure = { id: string; reason: string }; export type MutationResult = { affectedIds: string[]; failed: MutationFailure[] }; export type TrashPurgePlan = { id: string; mode: 'empty_all' | 'selected'; targetCount: number; expiresAt: string; destructive: true }; export type TrashPurgeMutationResult = MutationResult & { deletedCount: number; requestedCount: number; verified: boolean }; export type StackResolution = 'keep_existing' | 'move_selected' | 'include_existing'; export type StackResolutionMap = Record<string, StackResolution>; export type StackResolutionSelection = StackResolution | StackResolutionMap; export type StackConflict = { stackId: string; primaryAssetId?: string | null; memberAssetIds?: string[]; selectedAssetIds?: string[]; selectedCount: number; memberCount: number; includesUnselected: boolean }; export type StackActionPlan = { id: string; targetCount: number; primaryAssetId: string; conflicts: StackConflict[] }; export type DifferenceOptions = { hue?: number; contrast?: number; binary?: boolean }; export type MediaDelivery = 'original' | 'thumbnail' | 'preview' | 'decoded' | 'transcoded' | 'difference'; export type MediaPurpose = 'thumbnail' | 'view'; export type MediaResource = { url: string; fallbackUrls: string[]; mimeType: string | null; posterUrl: string | null; delivery: MediaDelivery; originalMimeType: string | null; expiresAt: string | null };
export type CollectionRequest = { pageSize: number; page?: number; cursor?: string | null; signal?: AbortSignal }; export type PageResult<T> = { items: T[]; total: number; pageSize: number; page?: number; nextCursor: string | null }; export type RelationOption = { value: string; label: string; subtitle: string }; export type OptionSearchQuery = { query?: string; pageSize: number; cursor?: string | null; signal?: AbortSignal }; export type OptionSearchResult = { items: RelationOption[]; nextCursor: string | null };
export type AssetRelationshipOption = RelationOption & { selectedAssetCount: number }; export type AssetSelectionRelationships = { albums: AssetRelationshipOption[]; tags: AssetRelationshipOption[] };
export type AssetSearchRule = { field: string; op: string; value: string }; export type AssetSearchGroup = { logic: 'AND' | 'OR'; negated: boolean; rules: AssetSearchRule[]; groups: AssetSearchGroup[] }; export type AssetSort = { field: 'takenDate' | 'filename'; direction: 'asc' | 'desc' }; export type AssetSimpleSearch = { filename?: string; mediaType?: 'Image' | 'Video' | ''; favorite?: 'Favorite' | 'Not favorite' | ''; archived?: 'Archived' | 'Not archived' | ''; albumIds?: string[]; tagIds?: string[]; noAlbum?: boolean; noTag?: boolean; takenAfter?: string; takenBefore?: string; minWidth?: string; maxWidth?: string; minHeight?: string; maxHeight?: string; minAspectRatio?: string; maxAspectRatio?: string }; export type AssetSearchCriteria = | { mode: 'simple'; filters: AssetSimpleSearch; sort: AssetSort } | { mode: 'expert'; rules: AssetSearchRule[]; groups: AssetSearchGroup[]; logic: 'AND' | 'OR'; negated: boolean; sort: AssetSort }; export type AssetSearchQuery = AssetSearchCriteria & CollectionRequest;
export type TrashSearchCriteria = { sort: { field: 'deletedAt' | 'takenAt' | 'name'; direction: 'asc' | 'desc' } }; export type TrashSearchQuery = TrashSearchCriteria & CollectionRequest; export type AlbumSearchQuery = CollectionRequest & { query?: string; sort: { field: 'name' | 'assets' | 'description'; direction: 'asc' | 'desc' } }; export type TagSearchQuery = CollectionRequest & { query?: string; includeHierarchy?: boolean; sort: { field: 'name' | 'path' | 'assets' | 'children'; direction: 'asc' | 'desc' } };
export type SavedSearchRecord = { id: string; name: string; description: string; criteria: AssetSearchCriteria; createdAt: string; updatedAt: string }; export type SavedSearchCreateInput = { name: string; description?: string; criteria: AssetSearchCriteria }; export type SavedSearchUpdateInput = { name?: string; description?: string; criteria?: AssetSearchCriteria }; export type SavedSearchQuery = CollectionRequest & { query?: string; sort?: { field: 'name' | 'updatedAt'; direction: 'asc' | 'desc' } };
export type SelectionEntityKind = 'asset' | 'album' | 'tag'; export type AssetSelectionWorkspace = { id: string; entityKind?: SelectionEntityKind; revision: number; selectedCount: number; status: 'active' | 'cancelled' | 'expired'; expiresAt: string }; export type AssetSelectionMembership = { selection: AssetSelectionWorkspace; selectedIds: string[] };
export type RelationSelectionCriteria = { query: string; includeHierarchy?: boolean };
export type CollectionDeleteItemResult = { id: string; status: 'completed' | 'skipped' | 'failed'; reason: string | null };
export type CollectionDeletePlan = { id: string; entityKind: 'album' | 'tag'; selectionId: string; targetDigest: string; targetCount: number; applicableCount: number; skippedCount: number; status: 'planned' | 'running' | 'partial' | 'completed' | 'failed' | 'expired'; expiresAt: string; results: CollectionDeleteItemResult[] };
export type AssetSelectionTarget = | { kind: 'ids'; ids: string[] } | { kind: 'query'; criteria: AssetSearchCriteria; excludedIds: string[] } | { kind: 'selection'; selectionId: string }; export type TrashSelectionTarget = | { kind: 'ids'; ids: string[] } | { kind: 'all'; excludedIds: string[] }; export type AssetSelectionCapabilities = { count: number; allFavorite: boolean; allArchived: boolean; hasTags: boolean; hasAlbums: boolean; hasStackMembers: boolean; canStack: boolean; singleAssetId: string | null; canSetStackPrimary: boolean; canRemoveCompleteStack: boolean }; export type ViewerNavigationWindow = { previousId: string | null; nextId: string | null; position: number | null; total: number };
export interface CrudRepository<TRecord, TCreateArgs extends unknown[], TUpdateInput> { getById(id: string): Promise<TRecord | undefined>; create(...args: TCreateArgs): Promise<TRecord | undefined>; update(id: string, patch: TUpdateInput): Promise<MutationResult>; delete(ids: readonly string[]): Promise<MutationResult> }
export interface AssetRepository { getById(id: string): Promise<AssetRecord | undefined>; details(id: string): Promise<AssetDetailRecord | undefined>; getMany(ids: readonly string[]): Promise<AssetRecord[]>; getTrashById(id: string): Promise<TrashAssetRecord | undefined>; search(query: AssetSearchQuery): Promise<PageResult<AssetRecord>>; searchTrash(query: TrashSearchQuery): Promise<PageResult<TrashAssetRecord>>; createSelection(): Promise<AssetSelectionWorkspace>; selectAllIntoSelection(selectionId: string, criteria: AssetSearchCriteria): Promise<AssetSelectionWorkspace>; updateSelectionMembers(selectionId: string, assetIds: readonly string[], selected: boolean, revision: number): Promise<AssetSelectionWorkspace>; selectionMembership(selectionId: string, assetIds: readonly string[]): Promise<AssetSelectionMembership | null>; materializeSelection(target: AssetSelectionTarget): Promise<string[]>; selectionCapabilities(target: AssetSelectionTarget, signal?: AbortSignal): Promise<AssetSelectionCapabilities>; removableRelationships(target: AssetSelectionTarget, signal?: AbortSignal): Promise<AssetSelectionRelationships>; setFavorite(target: AssetSelectionTarget, favorite: boolean): Promise<MutationResult>; setArchived(target: AssetSelectionTarget, archived: boolean): Promise<MutationResult>; sync(target: AssetSelectionTarget): Promise<MutationResult>; trash(target: AssetSelectionTarget): Promise<MutationResult>; restore(target: TrashSelectionTarget): Promise<MutationResult>; planTrashPurge(target: TrashSelectionTarget): Promise<TrashPurgePlan>; executeTrashPurge(planId: string): Promise<TrashPurgeMutationResult>; addToAlbum(target: AssetSelectionTarget, albumId: string): Promise<MutationResult>; removeFromAlbums(target: AssetSelectionTarget, albumIds?: readonly string[]): Promise<MutationResult>; addTags(target: AssetSelectionTarget, tagIds: readonly string[]): Promise<MutationResult>; removeTags(target: AssetSelectionTarget, tagIds?: readonly string[]): Promise<MutationResult>; planStack(target: AssetSelectionTarget, primaryAssetId: string, resolution?: StackResolutionSelection): Promise<StackActionPlan>; executeStack(planId: string): Promise<MutationResult>; stack(target: AssetSelectionTarget): Promise<MutationResult>; unstack(target: AssetSelectionTarget): Promise<MutationResult>; setStackPrimary(assetId: string): Promise<MutationResult>; removeCompleteStack(assetId: string): Promise<MutationResult> }
export interface RelationSelectionRepository { createSelection(): Promise<AssetSelectionWorkspace>; selectAllIntoSelection(selectionId: string, criteria: RelationSelectionCriteria): Promise<AssetSelectionWorkspace>; updateMatchingSelection(selectionId: string, criteria: RelationSelectionCriteria, selected: boolean, revision: number): Promise<AssetSelectionWorkspace>; matchingSelectionState(selectionId: string, criteria: RelationSelectionCriteria): Promise<{ matchingCount: number; selectedMatchingCount: number }>; updateSelectionMembers(selectionId: string, ids: readonly string[], selected: boolean, revision: number): Promise<AssetSelectionWorkspace>; selectionMembership(selectionId: string, ids: readonly string[]): Promise<AssetSelectionMembership | null>; planDelete(selectionId: string): Promise<CollectionDeletePlan>; executeDelete(planId: string): Promise<CollectionDeletePlan> }
export interface AlbumRepository extends CrudRepository<AlbumRecord, AlbumCreateArgs, AlbumUpdateInput>, RelationSelectionRepository { search(query: AlbumSearchQuery): Promise<PageResult<AlbumRecord>>; searchOptions(query: OptionSearchQuery): Promise<OptionSearchResult> }
export interface TagRepository extends CrudRepository<TagRecord, TagCreateArgs, TagUpdateInput>, RelationSelectionRepository { search(query: TagSearchQuery): Promise<PageResult<TagHierarchyRow>>; searchOptions(query: OptionSearchQuery): Promise<OptionSearchResult>; parentOptions(excludeTagId?: string): Promise<Array<{ value: string; label: string; subtitle: string }>> }
export interface SavedSearchRepository { getById(id: string): Promise<SavedSearchRecord | undefined>; search(query: SavedSearchQuery): Promise<PageResult<SavedSearchRecord>>; create(input: SavedSearchCreateInput): Promise<SavedSearchRecord>; update(id: string, patch: SavedSearchUpdateInput): Promise<MutationResult>; delete(ids: readonly string[]): Promise<MutationResult> }
export interface ViewerNavigationRepository { asset(currentId: string): Promise<ViewerNavigationWindow>; trash(currentId: string): Promise<ViewerNavigationWindow> }
export type MediaAsset = Pick<AssetRecord, 'id' | 'original_file_name' | 'original_mime_type' | 'width' | 'height' | 'asset_type'> | TrashAssetRecord; export interface MediaRepository { thumbnail(asset: MediaAsset): MediaResource; view(asset: MediaAsset): MediaResource; difference(selected: AssetRecord, reference: AssetRecord, options?: DifferenceOptions): Promise<MediaResource>; refresh(asset: MediaAsset, purpose: MediaPurpose): Promise<MediaResource> } export interface LegacyMediaRepository { thumbnail(asset: MediaAsset): string; fullSize(asset: MediaAsset): string; difference(selected: AssetRecord, reference: AssetRecord, options?: DifferenceOptions): string }
