version: "3.8"

services:
  companion:
    image: immich-companion:dev
    build:
      context: ..
      dockerfile: docker/Dockerfile
      target: development
    working_dir: /workspace/backend
    command:
      - uvicorn
      - companion.main:app
      - --host
      - 0.0.0.0
      - --port
      - "8080"
      - --no-access-log
      - --reload
      - --reload-dir
      - /workspace/backend/companion
    volumes:
      - ../backend:/workspace/backend:ro
