<script lang="ts">
  import iro from '@jaames/iro';
  import type { IroColorPicker } from '@jaames/iro/dist/ColorPicker';
  import { onMount, tick } from 'svelte';
  import { clickOutside } from '../../../lib/actions/clickOutside';
  import { floatingPopoverLayout, type FloatingPopoverLayout } from '../../../lib/utils/floatingPopover';
  import { clamp, colorFromHex, hslToHsv, hsvToRgb, normalizeHex, rgbToHex, rgbToHsv, type HsvColor, type RgbColor } from './colorMath';

  interface Props { value: string; onchange: (value: string) => void; }
  type ColorMode = 'hsv' | 'hsl' | 'rgb';
  type VisualMode = 'wheel' | 'rectangle';
  let { value, onchange }: Props = $props();
  let open = $state(false); let mode = $state<ColorMode>('rgb'); let visualMode = $state<VisualMode>('rectangle'); let recent = $state<string[]>([]); let hsv = $state<HsvColor>({ h: 220, s: 50, v: 100 });
  let anchor = $state<HTMLDivElement>(); let pickerContainer = $state<HTMLDivElement>(); let picker = $state<IroColorPicker | null>(null); let popoverLayout = $state<FloatingPopoverLayout | null>(null); let lastChromaticHue = $state(220);
  const presets = ['#EF4444', '#F97316', '#EAB308', '#22C55E', '#06B6D4', '#3B82F6'];
  const rgb = $derived(hsvToRgb(hsv)); const hsl = $derived(colorFromHex(rgbToHex(rgb)).hsl); const hex = $derived(rgbToHex(rgb));

  function remember(next: string): void { const normalized = normalizeHex(next); if (!normalized) return; recent = [normalized, ...recent.filter((item) => item !== normalized)].slice(0, 6); localStorage.setItem('immich-companion:recent-colors', JSON.stringify(recent)); }
  function setHsv(next: HsvColor, addRecent = false): void {
    const hue = next.s <= 0.001 || next.v <= 0.001 ? lastChromaticHue : ((next.h ?? lastChromaticHue) + 360) % 360;
    if (next.s > 0.001 && next.v > 0.001) lastChromaticHue = hue;
    hsv = { h: hue, s: clamp(next.s ?? 0, 0, 100), v: clamp(next.v ?? 0, 0, 100) }; const nextHex = rgbToHex(hsvToRgb(hsv));
    if (picker && picker.color.hexString.toUpperCase() !== nextHex) picker.color.set(nextHex); onchange(nextHex); if (addRecent) remember(nextHex);
  }
  function setRgb(next: RgbColor): void { const converted = rgbToHsv(next); setHsv({ ...converted, h: converted.s <= 0.001 ? lastChromaticHue : converted.h }); }
  function choose(next: string): void { const normalized = normalizeHex(next); if (!normalized) return; const converted = colorFromHex(normalized).hsv; setHsv({ ...converted, h: converted.s <= 0.001 ? lastChromaticHue : converted.h }, true); }
  function readPickerColor(color: iro.Color): void { const next = color.hsv; const saturation = next.s ?? 0; const value = next.v ?? 0; const hue = saturation <= 0.001 || value <= 0.001 ? lastChromaticHue : (next.h ?? lastChromaticHue); if (saturation > 0.001 && value > 0.001) lastChromaticHue = hue; hsv = { h: hue, s: saturation, v: value }; onchange(normalizeHex(color.hexString) ?? hex); }
  function destroyPicker(): void { if (picker) { picker.off('color:change', readPickerColor); picker = null; } if (pickerContainer) pickerContainer.replaceChildren(); }
  async function createPicker(): Promise<void> {
    destroyPicker(); await tick(); if (!open || !pickerContainer) return;
    const component = visualMode === 'wheel' ? iro.ui.Wheel : iro.ui.Box; const sliderType = visualMode === 'wheel' ? 'value' : 'hue'; const size = visualMode === 'wheel' ? 240 : 320; const rectangleHeight = 210;
    const created = iro.ColorPicker(pickerContainer, { width: size, boxHeight: rectangleHeight, layoutDirection: 'horizontal', color: hex, handleRadius: 9, activeHandleRadius: 11, sliderSize: 18, sliderMargin: 12, layout: [{ component, options: { wheelLightness: false } }, { component: iro.ui.Slider, options: { width: visualMode === 'wheel' ? size : rectangleHeight, sliderType, sliderShape: 'bar' } }] });
    picker = created;
    created.on('color:change', readPickerColor);
  }
  function updateField(channel: string, raw: string): void { const parsed = Number(raw); if (!Number.isFinite(parsed)) return; if (mode === 'rgb') setRgb({ ...rgb, [channel]: clamp(parsed, 0, 255) }); else if (mode === 'hsl') { const next = { ...hsl, [channel]: clamp(parsed, channel === 'h' ? 0 : 100, channel === 'h' ? 360 : 100) }; setHsv(hslToHsv(next)); } else setHsv({ ...hsv, [channel]: clamp(parsed, channel === 'h' ? 0 : 100, channel === 'h' ? 360 : 100) }); }
  function format(valueToFormat: number): string { return String(Math.round(valueToFormat * 10) / 10); }
  function updatePopoverLayout(): void { if (!open || !anchor) return; popoverLayout = floatingPopoverLayout(anchor.getBoundingClientRect(), window.innerWidth, window.innerHeight, { preferredWidth: 430, preferredHeight: 620, gap: 10 }); }
  function toggle(event: MouseEvent): void { event.preventDefault(); open = !open; if (open) requestAnimationFrame(() => { updatePopoverLayout(); void createPicker(); }); else destroyPicker(); }
  async function switchVisualMode(next: VisualMode): Promise<void> { if (visualMode === next) return; visualMode = next; await createPicker(); }
  function close(): void { open = false; destroyPicker(); remember(hex); }
  function suggestions(): string[] { return [30, 330, 180, 120, 0, 0].map((offset, index) => rgbToHex(hsvToRgb({ h: (hsv.h + offset) % 360, s: index === 4 ? Math.max(hsv.s - 25, 25) : hsv.s, v: index === 5 ? Math.max(hsv.v - 25, 25) : hsv.v }))); }
  onMount(() => { const initial = colorFromHex(value).hsv; lastChromaticHue = initial.s <= 0.001 || initial.v <= 0.001 ? 220 : initial.h; hsv = { ...initial, h: lastChromaticHue }; try { const saved = JSON.parse(localStorage.getItem('immich-companion:recent-colors') ?? '[]'); if (Array.isArray(saved)) recent = saved.filter((item): item is string => typeof item === 'string' && normalizeHex(item) !== null).map((item) => normalizeHex(item) as string).slice(0, 6); } catch { recent = []; } const onResize = () => { updatePopoverLayout(); picker?.resize(visualMode === 'wheel' ? 240 : 320); }; window.addEventListener('resize', onResize); window.addEventListener('scroll', updatePopoverLayout, true); return () => { window.removeEventListener('resize', onResize); window.removeEventListener('scroll', updatePopoverLayout, true); destroyPicker(); }; });
  $effect(() => { const external = normalizeHex(value); if (!external || external === hex) return; const converted = colorFromHex(external).hsv; lastChromaticHue = converted.s <= 0.001 || converted.v <= 0.001 ? lastChromaticHue : converted.h; hsv = { ...converted, h: converted.s <= 0.001 || converted.v <= 0.001 ? lastChromaticHue : converted.h }; if (picker && picker.color.hexString.toUpperCase() !== external) picker.color.set(external); });
</script>

<div class="picker" bind:this={anchor} use:clickOutside={{ enabled: open, onoutside: close }}>
  <button class="picker-current" type="button" aria-haspopup="dialog" aria-expanded={open} onclick={toggle}><span class="swatch" style={`background:${hex}`}></span><span>{hex}</span></button>
  {#if open && popoverLayout}
    <div class="picker-popup" style:left={`${popoverLayout.left}px`} style:top={popoverLayout.top === null ? 'auto' : `${popoverLayout.top}px`} style:bottom={popoverLayout.bottom === null ? 'auto' : `${popoverLayout.bottom}px`} style:width={`${popoverLayout.width}px`} style:max-height={`${popoverLayout.maxHeight}px`} role="dialog" aria-label="Choose a color">
      <input class="hex-input" autocomplete="off" data-1p-ignore data-bwignore="true" aria-label="HEX color" value={hex} oninput={(event) => { const normalized = normalizeHex(event.currentTarget.value); if (normalized) choose(normalized); }} />
      <div class="visual-toggle" role="group" aria-label="Visual picker mode"><button type="button" class:active={visualMode === 'rectangle'} onclick={() => switchVisualMode('rectangle')}>Rectangle</button><button type="button" class:active={visualMode === 'wheel'} onclick={() => switchVisualMode('wheel')}>Wheel</button></div>
      <div class="iro-host" bind:this={pickerContainer} aria-label={visualMode === 'wheel' ? 'Circular color picker' : 'Rectangular color picker'}></div>
      <div class="mode-switch" role="group" aria-label="Color value mode">{#each ['rgb', 'hsv', 'hsl'] as option}<button type="button" class:active={mode === option} onclick={() => (mode = option as ColorMode)}>{String(option).toUpperCase()}</button>{/each}</div>
      <div class="value-fields">{#if mode === 'rgb'}{#each [['r', rgb.r], ['g', rgb.g], ['b', rgb.b]] as field}<label>{String(field[0]).toUpperCase()}<input type="number" min="0" max="255" step="1" autocomplete="off" value={format(field[1] as number)} oninput={(event) => updateField(String(field[0]), event.currentTarget.value)} /></label>{/each}{:else if mode === 'hsl'}{#each [['h', hsl.h], ['s', hsl.s], ['l', hsl.l]] as field}<label>{String(field[0]).toUpperCase()}<input type="number" min="0" max={field[0] === 'h' ? '360' : '100'} step="1" autocomplete="off" value={format(field[1] as number)} oninput={(event) => updateField(String(field[0]), event.currentTarget.value)} /></label>{/each}{:else}{#each [['h', hsv.h], ['s', hsv.s], ['v', hsv.v]] as field}<label>{String(field[0]).toUpperCase()}<input type="number" min="0" max={field[0] === 'h' ? '360' : '100'} step="1" autocomplete="off" value={format(field[1] as number)} oninput={(event) => updateField(String(field[0]), event.currentTarget.value)} /></label>{/each}{/if}</div>
      <section><h3>Suggested</h3><div class="palette-grid">{#each suggestions() as suggestion}<button type="button" aria-label={`Use ${suggestion}`} title={suggestion} class="choice" onclick={() => choose(suggestion)}><span class="choice-dot" style={`background:${suggestion}`}></span><span>{suggestion}</span></button>{/each}</div></section>
      <section><h3>Recent</h3><div class="palette-grid">{#each recent.slice(0, 6) as recentColor}<button type="button" aria-label={`Use recent ${recentColor}`} title={recentColor} class="choice" onclick={() => choose(recentColor)}><span class="choice-dot" style={`background:${recentColor}`}></span><span>{recentColor}</span></button>{/each}</div></section>
      <section><h3>Common</h3><div class="palette-grid">{#each presets as preset}<button type="button" aria-label={`Use ${preset}`} title={preset} class="choice" onclick={() => choose(preset)}><span class="choice-dot" style={`background:${preset}`}></span><span>{preset}</span></button>{/each}</div></section>
    </div>
  {/if}
</div>

<style>
  .picker { position: relative; display: inline-block; width: 100%; } .picker-current { display: flex; width: 100%; gap: .6rem; align-items: center; padding: .65rem .75rem; border: 1px solid var(--color-border-subtle); border-radius: var(--radius-sm); color: inherit; background: var(--color-surface-raised); font: inherit; text-align: left; cursor: pointer; } .picker-current:hover, .picker-current:focus-visible { border-color: var(--color-accent-strong); } .swatch { width: 1.35rem; height: 1.35rem; flex: 0 0 auto; border: 1px solid var(--color-border-strong); border-radius: .35rem; }
  .picker-popup { position: fixed; z-index: 1200; display: grid; gap: .8rem; padding: 1rem; overflow: auto; border: 1px solid var(--color-border-strong); border-radius: var(--radius-md); background: var(--color-surface-raised); box-shadow: 0 1rem 3rem rgb(5 12 8 / 35%); scrollbar-color: var(--color-border-strong) transparent; scrollbar-width: thin; } .picker-popup::-webkit-scrollbar { width: .55rem; } .picker-popup::-webkit-scrollbar-track { margin: .6rem 0; background: transparent; } .picker-popup::-webkit-scrollbar-thumb { border: .15rem solid var(--color-surface-raised); border-radius: 999px; background: var(--color-border-strong); }
  .hex-input { width: 100%; box-sizing: border-box; padding: .65rem .75rem; border: 1px solid var(--color-border-subtle); border-radius: var(--radius-sm); font: inherit; text-transform: uppercase; color: inherit; background: var(--color-surface-raised); } .visual-toggle, .mode-switch { display: grid; grid-template-columns: repeat(2, 1fr); gap: .3rem; } .mode-switch { grid-template-columns: repeat(3, 1fr); } .visual-toggle button, .mode-switch button { padding: .45rem; border: 1px solid var(--color-border-subtle); border-radius: var(--radius-sm); color: var(--color-ink-muted); background: var(--color-canvas); cursor: pointer; font-size: .68rem; font-weight: 800; } .visual-toggle button.active, .mode-switch button.active { border-color: var(--color-accent-strong); color: var(--color-accent-strong); }
  .iro-host { display: flex; min-height: 0; align-items: center; justify-content: center; overflow: visible; } :global(.IroColorPicker) { max-width: 100%; } .value-fields { display: grid; grid-template-columns: repeat(3, 1fr); gap: .5rem; } label { display: grid; gap: .25rem; color: var(--color-ink-muted); font-size: .68rem; font-weight: 700; } label input[type='number'] { width: 100%; box-sizing: border-box; padding: .45rem; border: 1px solid var(--color-border-subtle); border-radius: var(--radius-sm); color: inherit; background: var(--color-surface-raised); font: inherit; }
  section { display: grid; gap: .4rem; } h3 { margin: 0; font-size: .72rem; } .palette-grid { display: grid; grid-template-columns: repeat(3, minmax(0, 1fr)); gap: .35rem; } .choice { display: flex; min-width: 0; gap: .35rem; align-items: center; padding: .25rem; overflow: hidden; border: 1px solid transparent; border-radius: var(--radius-sm); background: transparent; cursor: pointer; color: var(--color-ink-strong); font: inherit; font-size: .66rem; text-align: left; } .choice:hover, .choice:focus-visible { border-color: var(--color-accent-strong); background: var(--color-surface-soft); } .choice-dot { width: .95rem; height: .95rem; flex: 0 0 auto; border: 1px solid var(--color-border-strong); border-radius: 50%; } .choice span:last-child { min-width: 0; overflow: hidden; text-overflow: ellipsis; white-space: nowrap; }
</style>
