<script lang="ts">
  import V2PageLayout from '../components/V2PageLayout.svelte'; import V2Tabs from '../components/V2Tabs.svelte'; import V2Zone from '../components/V2Zone.svelte'; import V2ZoneLabel from '../components/V2ZoneLabel.svelte'; import V2Stack from '../components/V2Stack.svelte'; import V2Inline from '../components/V2Inline.svelte'; import V2Card from '../components/V2Card.svelte'; import V2Badge from '../components/V2Badge.svelte'; import V2Section from '../components/V2Section.svelte'; import V2Field from '../components/V2Field.svelte'; import V2AssetTile from '../components/V2AssetTile.svelte'; import V2Pagination from '../components/V2Pagination.svelte'; import V2Viewer from '../components/V2Viewer.svelte';
  let tab=$state('Browse'), searchMode=$state<'Simple'|'Expert'>('Simple'), page=$state(1), pageSize=$state(24), resultMode=$state<'Pagination'|'Infinite'>('Pagination'), loaded=$state(24), viewer=$state(false), drawer=$state(false), summary=$state('Simple search · current filters'); const total=2418;
  const start=$derived((page-1)*pageSize); const count=$derived(resultMode==='Pagination'?Math.min(pageSize,total-start):Math.min(loaded,total)); const ids=$derived(Array.from({length:count},(_,i)=>resultMode==='Pagination'?start+i:i));
  function setMode(mode:'Pagination'|'Infinite'){resultMode=mode;if(mode==='Pagination')page=1;else loaded=Math.max(pageSize,loaded)}
</script>
<V2PageLayout title="Assets" description="Search, browse, select, synchronize and perform guarded actions on assets.">
  {#snippet headerActions()}<V2Inline gap="sm"><button class="v2-button">Sync selected</button><button class="v2-button v2-button-primary">Actions</button></V2Inline>{/snippet}
  {#snippet tabs()}<V2Tabs items={['Browse','Saved searches']} active={tab} onselect={(v)=>tab=v}/>{/snippet}
  {#snippet context()}<V2Zone label="Context rail"><V2Section title="Search mode"><V2Inline gap="sm"><button class="v2-button" class:v2-button-primary={searchMode==='Simple'} onclick={()=>searchMode='Simple'}>Simple</button><button class="v2-button" class:v2-button-primary={searchMode==='Expert'} onclick={()=>searchMode='Expert'}>Expert</button></V2Inline></V2Section>{#if searchMode==='Simple'}<V2Section title="Filters"><V2Stack gap="sm"><V2Field label="Filename" placeholder="Filename contains…"/><V2Field label="Media type" options={['Any','Image','Video']}/><V2Field label="Favorite" options={['Any','Favorite','Not favorite']}/><V2Field label="Archived" options={['Any','Archived','Not archived']}/><button class="v2-button">Advanced filters</button></V2Stack></V2Section>{:else}<V2Section title="Expert search"><V2Stack gap="sm"><V2Badge text="Boolean"/><V2Field label="Saved expert search" options={['Choose saved search…','Favorite images not archived','Family album or Vacation tag','Large landscape images']}/><V2Card><V2Stack gap="sm"><V2Inline justify="between"><b>Current expression</b><V2Badge text="4 rules · 1 group"/></V2Inline><span class="v2-small v2-muted">(Media type is Image AND Favorite is true) AND (Album is Family OR Tag is Vacation)</span><button class="v2-button" onclick={()=>drawer=true}>Edit expression</button></V2Stack></V2Card></V2Stack></V2Section>{/if}<V2Inline gap="sm"><button class="v2-button v2-button-primary" onclick={()=>summary=`${searchMode} search · submitted filters`}>Search assets</button><button class="v2-button" onclick={()=>summary=`${searchMode} search · cleared and reloaded`}>Clear</button></V2Inline></V2Zone>{/snippet}
  <V2Zone><V2Inline justify="between" align="start" wrap={true}><V2Inline gap="sm" wrap={true}><V2ZoneLabel text="Primary content"/><V2Badge text={`${total.toLocaleString()} matches`}/><button class="v2-button">Select loaded</button><button class="v2-button">Select all matching</button><button class="v2-button">Invert</button></V2Inline><V2Inline gap="sm" wrap={true}><select class="v2-select-auto"><option>Taken date ↓</option></select><select class="v2-select-auto" value={pageSize} onchange={(e)=>{pageSize=Number(e.currentTarget.value);page=1;loaded=pageSize}}><option value="24">24 / batch</option><option value="48">48 / batch</option><option value="96">96 / batch</option></select><div class="v2-segmented"><button class:active={resultMode==='Pagination'} onclick={()=>setMode('Pagination')}>Pagination</button><button class:active={resultMode==='Infinite'} onclick={()=>setMode('Infinite')}>Infinite</button></div></V2Inline></V2Inline><div class="v2-asset-grid">{#each ids as id}<V2AssetTile index={id} label={`IMG_${String(id+1).padStart(4,'0')}.jpg`} sublabel={`Aug ${21-(id%8)}, 2026`} onclick={()=>viewer=true}/>{/each}</div>{#if resultMode==='Pagination'}<V2Pagination {page} {pageSize} {total} onpage={(p)=>page=p}/>{:else}<div class="v2-infinite-sentinel"><div>{loaded>=total?`All ${total.toLocaleString()} matching assets loaded`:`${loaded.toLocaleString()} of ${total.toLocaleString()} loaded`}</div>{#if loaded<total}<button class="v2-button" onclick={()=>loaded=Math.min(total,loaded+pageSize)}>Load next {pageSize}</button>{/if}</div>{/if}</V2Zone>
  {#snippet inspector()}<V2Zone label="Inspector"><V2Section title="Active search"><V2Card><span class="v2-small">{summary}</span></V2Card></V2Section><V2Section title="Selection"><V2Card><b>3 assets selected</b><p class="v2-small v2-muted">Resolved selection summary and applicable actions.</p></V2Card></V2Section><V2Section title="Actions"><V2Stack gap="sm"><button class="v2-button">Add to album</button><button class="v2-button">Favorite</button><button class="v2-button">Archive</button><button class="v2-button">Stack</button><button class="v2-button">Add tags</button><button class="v2-button v2-button-danger">Move to trash</button></V2Stack></V2Section></V2Zone>{/snippet}
</V2PageLayout>
<V2Viewer open={viewer} title="Assets Viewer" mode="assets" onclose={()=>viewer=false}/>
{#if drawer}<div class="v2-drawer-backdrop" onclick={()=>drawer=false}></div><aside class="v2-drawer"><div class="v2-drawer-head"><div><V2ZoneLabel text="Expert search editor"/><h2>Build asset search expression</h2><p class="v2-muted">Edit the draft here. Results change only when you apply/search.</p></div><button class="v2-button" onclick={()=>drawer=false}>✕</button></div><div class="v2-drawer-body"><V2Section title="Expression structure"><V2Stack gap="md"><V2Card><V2Inline justify="between"><V2Badge text="Root group"/><div class="v2-segmented"><button class="active">AND</button><button>OR</button></div></V2Inline><V2Stack gap="sm"><V2Field label="Rule 1" value="Image"/><V2Field label="Rule 2" value="true"/><button class="v2-button">+ Rule</button><button class="v2-button">+ Nested group</button></V2Stack></V2Card><V2Card><V2Badge text="Nested group"/><V2Field label="Album" value="Family"/><V2Field label="Tag" value="Vacation"/></V2Card></V2Stack></V2Section><V2Section title="Expression preview"><div class="v2-expression">(Media type is Image AND Favorite is true) AND (Album is Family OR Tag is Vacation)</div></V2Section></div><div class="v2-drawer-foot"><V2Badge text="4 rules · 1 group"/><V2Inline gap="sm"><button class="v2-button">Reset</button><button class="v2-button" onclick={()=>drawer=false}>Cancel</button><button class="v2-button v2-button-primary" onclick={()=>{drawer=false;summary='Expert search · applied expression'}}>Apply & Search</button></V2Inline></div></aside>{/if}
