"""Refresh the composite duplicate projection with compact similarity group IDs.

Revision ID: 20260925_0061
Revises: 20260924_0060
"""

from __future__ import annotations

from alembic import op

revision = "20260925_0061"
down_revision = "20260924_0060"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # Group identity is generated by discovery code rather than migrated in place.
    # Mark the projection stale so startup reconciliation atomically republishes it
    # with compact IDs while preserving review/workspace identity via stable_group_key.
    op.execute(
        """
        UPDATE composite_duplicate_sync_state
        SET last_success_at = NULL
        """
    )


def downgrade() -> None:
    # There is no safe timestamp to restore. A later startup reconciliation may
    # republish the projection with whatever identity format that code version uses.
    pass
