import type { DuplicateSearchQuery, SimilarityCacheStatus } from '../types/contracts';
import type { ApiDuplicateHistoryItem, ApiDiskCacheStatus, ApiSimilarityCacheStatus } from './duplicateRepository';

export function cacheStatus(value: ApiSimilarityCacheStatus): SimilarityCacheStatus {
  const disk = (entry: ApiDiskCacheStatus) => ({ path: entry.path, healthy: entry.healthy, usedBytes: entry.used_bytes, maxBytes: entry.max_bytes, freeBytes: entry.free_bytes, entryCount: entry.entry_count, hits: entry.hits, misses: entry.misses, evictions: entry.evictions, cleanupFailures: entry.cleanup_failures });
  return { configFingerprint: value.config_fingerprint, featureCount: value.feature_count, featureEstimatedBytes: value.feature_estimated_bytes, pairCount: value.pair_count, pairEstimatedBytes: value.pair_estimated_bytes, pairMaxBytes: value.pair_max_bytes, pairHits: value.pair_hits, pairMisses: value.pair_misses, pairEvictions: value.pair_evictions, hotCount: value.hot_count, hotEstimatedBytes: value.hot_estimated_bytes, hotMaxBytes: value.hot_max_bytes, hotHits: value.hot_hits, hotMisses: value.hot_misses, hotEvictions: value.hot_evictions, referenceLatencyP50Ms: value.reference_latency_p50_ms, referenceLatencyP95Ms: value.reference_latency_p95_ms, previews: disk(value.previews), decode: disk(value.decode), generatedAt: value.generated_at };
}
export function pageNumber(query: DuplicateSearchQuery): number { if (query.page) return query.page; const cursor = Number.parseInt(query.cursor ?? '', 10); return Number.isSafeInteger(cursor) && cursor > 0 ? cursor : 1; }
export function historyDays(range: 'Last 30 days' | 'Last 90 days' | 'All history'): number | null { if (range === 'Last 30 days') return 30; if (range === 'Last 90 days') return 90; return null; }
export function historySummary(item: ApiDuplicateHistoryItem): string { const count = item.member_count; if (item.review_status === 'reviewed_keep_all') return `Kept all ${count} duplicate assets`; if (item.review_status === 'reviewed_stack_all') return `Stacked ${count} duplicate assets`; if (item.review_status === 'reviewed_mixed') return `Applied mixed decisions to ${count} duplicate assets`; return `Resolved ${count} duplicate assets`; }
export function reviewStateParam(state: DuplicateSearchQuery['state']): string { if (!state || state === 'All groups' || state === 'Selected') return 'all'; if (state === 'Needs review') return 'needs_review'; if (state === 'Auto-ready') return 'auto_ready'; if (state === 'Blocked') return 'blocked'; if (state === 'Actionable') return 'actionable'; return 'needs_decisions'; }
