import type { DuplicateDecision, DuplicateSource } from '../types/contracts';

export type AnalysisOptions = { keeper_policy: 'prefer_upload'; external_library_ids: string[]; verify_upload_streams: boolean; automatic_handling_enabled: boolean; preselect_safe_groups: boolean; exact_file_action: 'resolve'; analyze_automatically: boolean };
export type ApiDuplicateMember = { id: string; source_kind: 'upload' | 'external'; library_id: string | null; original_file_name: string; original_mime_type: string | null; file_size_bytes: number | null; file_modified_at: string; uploaded_at: string | null; is_offline: boolean; is_stacked: boolean; verification: 'matching' | 'mismatch' | 'unverified'; evidence: { decoded_width?: number | null; decoded_height?: number | null }; similarity: { state: 'reference' | 'current' | 'pending' | 'unavailable'; similarity_percent: number | null; structural_percent: number | null; perceptual_percent: number | null; color_percent: number | null; normalized_luminance_mae?: number | null; normalized_luminance_rmse?: number | null; normalized_luminance_ssim?: number | null; aspect_ratio_difference?: number | null; dimensions_equal?: boolean | null; exact_thumbnail_match?: boolean | null; exact_pixel_match?: boolean | null; detail_changed_percent?: number | null; detail_source?: 'original' | 'transcoded' | 'preview' | null; validated_width?: number | null; validated_height?: number | null; reference_validated_width?: number | null; reference_validated_height?: number | null; model_version?: string | null; feature_version?: number | null; comparison_version?: number | null } | null; admission: { admitted_by_asset_id: string | null; admission_similarity_percent: number | null; best_group_match_asset_id: string | null; best_group_match_similarity_percent: number | null; link_depth: number; model_version: string; feature_version: number; comparison_version: number; config_fingerprint: string } | null; preservation: { origin: 'original' | 'preview'; pixel_normalization_version: number; pixel_sha256: string; decoded_width: number; decoded_height: number; bit_depth: number; channel_count: number; has_alpha: boolean; color_space: string; orientation: number | null; icc_profile_present: boolean; has_exif: boolean; has_capture_time: boolean; has_camera_info: boolean; has_gps: boolean; has_orientation_metadata: boolean; metadata_richness: number } | null };
export type ApiDuplicateKeeperSelectionResult = { matched_group_count: number; valid_group_count: number; resolved_group_count: number; would_apply_group_count: number; applied_group_count: number; ambiguous_group_count: number; blocked_group_count: number; preserved_manual_group_count: number; missing_group_count: number; keeper_count: number; trash_count: number; limit_exceeded: boolean };
export type ApiDuplicateGroup = { group_id: string; discovery_source: DuplicateSource; discovery_sources?: DuplicateSource[]; reference_asset_id: string | null; group_similarity_percent: number | null; similarity_engine: string | null; similarity_model_version: string | null; similarity_feature_version: number | null; similarity_comparison_version: number | null; similarity_validation_mode: 'reference' | 'linked' | 'strict' | null; similarity_threshold_percent: number | null; classification: 'exact_file' | 'exact_pixels' | 'likely_same' | 'similar' | 'mismatch' | 'unverified' | 'unavailable' | 'ineligible'; status: 'exact' | 'unverified' | 'mismatch' | 'ineligible'; reason: string | null; auto_resolvable: boolean; auto_selected: boolean; member_fingerprint: string; members: ApiDuplicateMember[]; eligible: boolean };
export type ApiDuplicateSummary = { group_count: number; member_count: number };
export type ApiDuplicateGroupIds = { group_ids: string[]; limit_exceeded: boolean };
export type ApiDuplicatePage = { items: ApiDuplicateGroup[]; total: number; page: number; page_size: number; pages: number };
export type ApiDuplicateDraft = { group_id: string; member_fingerprint: string; decisions: Array<{ asset_id: string; disposition: DuplicateDecision; source?: 'manual' | 'automatic'; status?: 'pending' | 'completed' }>; stack_primary_asset_id: string | null; stack_resolution: string; metadata_keeper_asset_id?: string | null; status: 'pending' | 'completed'; stale: boolean };
export type ApiDuplicateWorkspace = { initialized: boolean; revision?: number; selected_count?: number; selected_group_ids: string[]; active_group_id: string | null; stale_selected_groups: Array<{ group_id: string }>; drafts: ApiDuplicateDraft[]; last_applied_group_ids?: string[]; last_skipped_group_ids?: string[]; cleared_group_count?: number };
export type ApiDuplicateHistoryItem = { id: string; occurred_at: string; discovery_source: DuplicateSource; provider_group_id: string; review_status: 'reviewed_keep_all' | 'reviewed_resolve' | 'reviewed_stack_all' | 'reviewed_mixed'; manual_action: string | null; member_count: number; member_asset_ids: string[] };
export type ApiDuplicateHistoryPage = { items: ApiDuplicateHistoryItem[]; total: number; page: number; page_size: number; pages: number };
export type TaskStart = { task_id: string };
export type ApiDuplicatePlanStack = { primary_asset_id: string; member_asset_ids: string[]; resolution?: string };
export type PlanResponse = { id: string; destructive?: boolean; groups?: Array<{ group_id: string; members: Array<{ asset_id: string; disposition: DuplicateDecision }>; follow_up?: ApiDuplicatePlanStack | null; follow_ups?: ApiDuplicatePlanStack[] }> };
export type ApiDiskCacheStatus = { path:string;healthy:boolean;used_bytes:number;max_bytes:number;free_bytes:number;entry_count:number;hits:number;misses:number;evictions:number;cleanup_failures:number };
export type ApiSimilarityCacheStatus = { config_fingerprint:string;feature_count:number;feature_estimated_bytes:number;pair_count:number;pair_estimated_bytes:number;pair_max_bytes:number;pair_hits:number;pair_misses:number;pair_evictions:number;hot_count:number;hot_estimated_bytes:number;hot_max_bytes:number;hot_hits:number;hot_misses:number;hot_evictions:number;reference_latency_p50_ms:number|null;reference_latency_p95_ms:number|null;previews:ApiDiskCacheStatus;decode:ApiDiskCacheStatus;generated_at:string };
export type ApiSimilarityCacheClearResult = { status: ApiSimilarityCacheStatus };
